In [1]:
# Lasciate questa cella così ogni volta che aggiornate un file python, 
# anche gli import nel notebook vengono aggiornati

%load_ext autoreload
%autoreload 2

In [92]:
import numpy as np

from Utils import *
from constants import *

from Environment import *
from Non_Stationary_Environment import *

from Social_influence import *
from Network import Network

from Simulation import *

from Ecommerce import *
from Ecommerce3 import *
from Ecommerce4 import *
from Ecommerce5 import *
from Ecommerce6 import *

## Step 2

In [3]:
simulate_step2()

optimal allocation is: [60. 60. 20. 60.  0.] with a reward of: 457
estimated_opt_allocation is: [60. 60. 20. 60.  0.] with a reward of: 457


## Step 3

In [ ]:
gpts_rewards_per_experiment, gpucb_rewards_per_experiment, opts = simulate_step3()
plot_regrets(gpts_rewards_per_experiment, gpucb_rewards_per_experiment, opts, ["GPTS", "GPUCB"])

## Step 4

In [11]:
gpts_rewards_per_experiment, gpucb_rewards_per_experiment, opts = simulate_step4()
plot_regrets(gpts_rewards_per_experiment, gpucb_rewards_per_experiment, opts, ["GPTS", "GPUCB"])

## Step 5

In [ ]:
gpucb_rewards_per_experiment, gpts_rewards_per_experiment, opts = simulate_step5()
plot_regrets(gpts_rewards_per_experiment, gpucb_rewards_per_experiment, opts, ["GPTS", "GPUCB"])

## Step 6

In [ ]:
swucb_rewards_per_experiment, cducb_rewards_per_experiment, opts = simulate_step6()
plot_regrets(swucb_rewards_per_experiment, cducb_rewards_per_experiment, opts, ["SWUCB", "CDUCB"])

## Step 7

In [101]:
B_cap = 100
budgets = np.arange(start=0, stop=B_cap + 1, step=5)

In [102]:
env, observations_probabilities, click_probabilities, product_prices,\
    users_reservation_prices, users_poisson_parameters = generate_new_environment()

In [103]:
nodes_activation_probabilities, num_sold_items = estimate_nodes_activation_probabilities(
        click_probabilities,
        users_reservation_prices,
        users_poisson_parameters,
        product_prices,
        observations_probabilities
    )

In [105]:
dis_exp_num_clicks = env.estimate_disaggregated_num_clicks(budgets/B_cap)

In [106]:
aggr_exp_num_clicks = env.estimate_num_of_clicks(budgets/B_cap)

In [107]:
ecomm = Ecommerce(B_cap, budgets, product_prices)
print(ecomm.solve_optimization_problem(num_sold_items, aggr_exp_num_clicks, nodes_activation_probabilities))

(array([10, 55, 20, 15,  0]), 477.9532094248543)


In [108]:
ecomm = Ecommerce(B_cap, budgets, product_prices)
print(ecomm.solve_disaggregated_optimization_problem(num_sold_items, dis_exp_num_clicks, nodes_activation_probabilities))

(array([[ 0,  0,  0,  5,  0],
       [10,  0, 20, 20,  0],
       [ 0,  0,  0,  5,  0]]), 28.209127094482923)


In [109]:
ecomm = Ecommerce(B_cap, budgets, product_prices)
for i in range(3):
    print(ecomm.solve_optimization_problem(num_sold_items, dis_exp_num_clicks[i], nodes_activation_probabilities))

(array([15, 40, 20,  5,  0]), 76.76420991153478)
(array([10, 40, 20, 20,  0]), 125.43946596548119)
(array([ 0, 55, 25, 20,  0]), 146.1456479942379)
